### ISSUE TITLE
streams don't play

### ISSUE THREAD

**Issue by chovy** [awaters1/plugin.video.espn_3#2]
I upgraded to latest from master and streams still don't play.
I have an account configured, but its still telling me there's no account associated.

http://xbmclogs.com/pagdlpxtm

**Comment by awaters1** [comment]
Thank you for the report.  I see in the logs it says

17:01:20 T:123145305063424  NOTICE: EPSN3: Fixing up data because of no xml preamble
17:01:26 T:140735281532928   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.espn_3/?EVENT_ID=2778469&SIMULCAST_AIRING_ID=18915212&DESKTOP_STREAM_SOURCE=HDS&MODE=PLAY&NETWORK_ID=n501]

Can you enable debug logging to get the contents between those two messages?  I also recently made a commit 35134f1 that may have fixed it.

**Comment by chovy** [comment]
How do I enable debug logging?

**Comment by awaters1** [comment]
There is a good tutorial here http://kodi.wiki/view/Log_file/Easy I plan on testing out a few different scenarios, which provider did you try?

**Comment by chovy** [comment]
This is with Xfinity/Comcast

**Comment by awaters1** [comment]
Thanks, I'm working on tweaking the code now to be more resilient for other providers.

**Comment by chovy** [comment]
cool let me know when you have something for me to test.

**Comment by awaters1** [comment]
Try the latest from master, I redid the authentication mechanism but I haven't tested it fully.

**Comment by chovy** [comment]
still doesn't play

**Comment by awaters1** [comment]
Should be fixed with the latest from master, the authentication system was re-done to match the new style of authorizing devices.
